In [5]:
import torch

In [6]:
tensor = torch.tensor([1, 2, 3, 4, 5])
print(tensor.shape)
s = torch.sum(tensor, dim=0)
print(s)
print(s.shape)

torch.Size([5])
tensor(15)
torch.Size([])


In [16]:
tensor = torch.tensor([
    [1, 2, 3], [4, 5, 6]
])

print(tensor.shape) # torch.Size([2, 3])
print()

print("Dimension: 0")
dim0 = torch.sum(tensor, dim=0)
print(dim0) # tensor([5, 7, 9])
print(dim0.shape) # torch.Size([3])
print()

print("Dimension: 1")
dim1 = torch.sum(tensor, dim=1) 
print(dim1) # tensor([6, 15])
print(dim1.shape) # torch.Size([2])
print()

print("Dimension: -1")
dims = torch.sum(tensor, dim=-1)
print(dims) # tensor([6, 15])
print(dims.shape) # torch.Size([2])

torch.Size([2, 3])

Dimension: 0
tensor([5, 7, 9])
torch.Size([3])

Dimension: 1
tensor([ 6, 15])
torch.Size([2])

Dimension: -1
tensor([ 6, 15])
torch.Size([2])


In [21]:
tensor = torch.tensor([
    [[1, 2, 9], [3, 4, 0]],
    [[5, 6, 1], [7, 8, 2]]
])

print(tensor.shape) # torch.Size([2, 2, 3])
print()

print("Dimension: 0")
dim0 = torch.sum(tensor, dim=0)
print(dim0) # tensor([[ 6,  8, 10], [10, 12,  2]])
print(dim0.shape) # torch.Size([2, 3])
print()

print("Dimension: 1")
dim1 = torch.sum(tensor, dim=1)
print(dim1) # tensor([[ 4,  6,  9], [12, 14,  3]])
print(dim1.shape) # torch.Size([2, 3])
print()

print("Dimension: 2")
dim2 = torch.sum(tensor, dim=2)
print(dim2) # tensor([[12,  7], [12, 17]])
print(dim2.shape) # torch.Size([2, 2])

torch.Size([2, 2, 3])

Dimension: 0
tensor([[ 6,  8, 10],
        [10, 12,  2]])
torch.Size([2, 3])

Dimension: 1
tensor([[ 4,  6,  9],
        [12, 14,  3]])
torch.Size([2, 3])

Dimension: 2
tensor([[12,  7],
        [12, 17]])
torch.Size([2, 2])


In [ ]:
tensor = torch.tensor([
    [
        [
            [1, 2],
            [3, 4],
            [5, 6]
        ],
        [
            [7, 8],
            [9, 10],
            [1, 2]
        ]
    ],
    [
        [
            [3, 4],
            [5, 6],
            [7, 8]
        ],
        [
            [9, 0],
            [1, 2],
            [3, 4]
        ]
    ],
    [
        [
            [5, 6],
            [7, 8],
            [9, 0]
        ],
        [
            [1, 2],
            [3, 4],
            [5, 6]
        ]
    ]
])

print(tensor.shape) # torch.tensor([3, 2, 3, 2])
print()

print("Dimension: 0")
dim0 = torch.sum(tensor, dim=0)
print(dim0) # tensor([[[ 9, 12], [15, 18], [21, 14]], [[17, 10], [13, 16], [ 9, 12]]])
print(dim0.shape) # torch.Size([2, 3, 2])
print()

print("Dimension: 1")
dim1 = torch.sum(tensor, dim=1)
print(dim1) # tensor([[[ 8, 10], [12, 14], [ 6,  8]], [[12,  4], [ 6,  8], [10, 12]], [[ 6,  8], [10, 12], [14,  6]]])
print(dim1.shape) # torch.Size([3, 3, 2])
print()

print("Dimension: 2")
dim2 = torch.sum(tensor, dim=2)
print(dim2) # tensor([[[ 9, 12], [17, 20]], [[ 15, 18], [13, 6]], [[21, 14], [ 9, 12]]])
print(dim2.shape) # torch.Size([3, 2, 2])
print()

print("Dimension: 3")
dim3 = torch.sum(tensor, dim=3)
print(dim3) # tensor([[[ 3,  7, 11], [15, 19,  3]], [[ 7, 11, 15], [ 9,  3,  7]], [[11, 15,  9], [ 3,  7, 11]]])
print(dim3.shape) # torch.Size([3, 2, 3])

torch.Size([3, 2, 3, 2])

Dimension: 0
tensor([[[ 9, 12],
         [15, 18],
         [21, 14]],

        [[17, 10],
         [13, 16],
         [ 9, 12]]])
torch.Size([2, 3, 2])

Dimension: 1
tensor([[[ 8, 10],
         [12, 14],
         [ 6,  8]],

        [[12,  4],
         [ 6,  8],
         [10, 12]],

        [[ 6,  8],
         [10, 12],
         [14,  6]]])
torch.Size([3, 3, 2])

Dimension: 2
tensor([[[ 9, 12],
         [17, 20]],

        [[15, 18],
         [13,  6]],

        [[21, 14],
         [ 9, 12]]])
torch.Size([3, 2, 2])

Dimension: 3
tensor([[[ 3,  7, 11],
         [15, 19,  3]],

        [[ 7, 11, 15],
         [ 9,  3,  7]],

        [[11, 15,  9],
         [ 3,  7, 11]]])
torch.Size([3, 2, 3])


In [ ]:
tensor = torch.tensor([
    [[1, 2, 9], [3, 4, 0]],
    [[5, 6, 1], [7, 8, 2]]
])

print(tensor.shape) # torch.Size([2, 2, 3])
print()

dim0 = torch.any(tensor < 2, dim=0)
print(dim0) # tensor([[True, False, True], [False, False, True]])
print(dim0.shape) # torch.Size([2, 3])
print()

dim1 = torch.any(tensor < 2, dim=1)
print(dim1) # tensor([[True, False, True], [False, False, True]])
print(dim1.shape) # torch.Size([2, 3])
print()

dim2 = torch.any(tensor < 2, dim=2)
print(dim2) # tensor([[True, True], [True, False]])
print(dim2.shape) # torch.Size([2, 2])

torch.Size([2, 2, 3])

tensor([[ True, False,  True],
        [False, False,  True]])
torch.Size([2, 3])

tensor([[ True, False,  True],
        [False, False,  True]])
torch.Size([2, 3])

tensor([[ True,  True],
        [ True, False]])
torch.Size([2, 2])
